### ISSUE TITLE
Deploy self-hosted runner

### ISSUE THREAD

**Issue by nicklasfrahm** [nicklasfrahm/infrastructure#13]
For my project [`k3se`](https://github.com/nicklasfrahm/k3se) I need a self-hosted GitHub Actions runner so I can run automated tests via Vagrant.

**Comment by aktech** [comment]
2 cents on self-hosting runners:

I built a service for running self-hosted GitHub Action runners on cloud with 0 maintenance and free for open source: https://cirun.io/

It's on-demand, which means you only pay to your cloud provider for the time you're using it.
All you need is a simple configuration .cirun.yml file, here is a [demo](https://www.youtube.com/watch?v=lDx0YVTn6yg).
Also available on GitHub Marketplace as well: https://github.com/marketplace/cirun-io

**Comment by nicklasfrahm** [comment]
@aktech Thank you, your project is very interesting in general, but I would prefer to run the runner on my own on-premises infrastructure.

**Comment by aktech** [comment]
Cirun provides a way to do that via Openstack, just in case :)

**Comment by nicklasfrahm** [comment]
Closing this for now as I won't prioritize this any time soon.
